
---
version: '3'
services:

  mssql-cloud:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    hostname: mssql-cloud
    container_name: mssql-cloud
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Fender2000'

  connect-onprem:
    image: kafka-connect-idstudios:1.0.0 
    hostname: connect-onprem
    container_name: connect-onprem
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "pkc-ld537.ca-central-1.aws.confluent.cloud:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-onprem
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 3
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.3.0.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR  

      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "https://psrc-6zww3.us-east-2.aws.confluent.cloud"
      CONNECT_KEY_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "${SR_USER}:${SR_PASSWORD}"
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "https://psrc-6zww3.us-east-2.aws.confluent.cloud"
      CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "${SR_USER}:${SR_PASSWORD}"
      CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'

      # Confluent Cloud config
      CONNECT_REQUEST_TIMEOUT_MS: "30000"
      CONNECT_RETRY_BACKOFF_MS: "500"
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_SASL_MECHANISM: "PLAIN"
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${CCLOUD_USER}\" password=\"${CCLOUD_PASSWORD}\";"
      #
      CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${CCLOUD_USER}\" password=\"${CCLOUD_PASSWORD}\";"
      CONNECT_CONSUMER_REQUEST_TIMEOUT_MS: "30000"
      CONNECT_CONSUMER_RETRY_BACKOFF_MS: "500"
      #
      CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${CCLOUD_USER}\" password=\"${CCLOUD_PASSWORD}\";"
      CONNECT_PRODUCER_REQUEST_TIMEOUT_MS: "30000"
      CONNECT_PRODUCER_RETRY_BACKOFF_MS: "500"

      MSSQL_HOST: "${MSSQL_HOST}"
      MSSQL_DBNAME: "${MSSQL_DBNAME}"
      MSSQL_TABLE: "${MSSQL_TABLE}"
      MSSQL_PORT: "${MSSQL_PORT}"
      MSSQL_USER: "${MSSQL_USER}"
      MSSQL_PASSWORD: "${MSSQL_PASSWORD}"
      TOPIC_PREFIX: "${TOPIC_PREFIX}"
      HISTORY_TOPIC_NAME: "${HISTORY_TOPIC_NAME}"
      INTERNAL_TOPIC_NAME: "${INTERNAL_TOPIC_NAME}"

    command:
      - bash
      - -c
      - |
        echo -e
        echo -e "Bootstrap server: $${CONNECT_BOOTSTRAP_SERVERS}"
        sleep 5

        echo "Launching Kafka Connect worker"
        /etc/confluent/docker/run &
        sleep infinity

