---
version: '3.5'
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    hostname: mssql
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Fender2000'
    networks:
        - confluent_default

networks:
  confluent_default:
    external: true
